name: Integration Tests

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - 2025-updates

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397589511426:role/account-wide-resources-GithubActionsRole-1CAIKQPYM5WD3
          aws-region: ${{ env.AWS_REGION }}

      - run: ./test-harness/deploy-all.sh

      - run: ./test-harness/test-all.sh

# TODO - add this back when ready
#      - if: always()
#        run: ./test-harness/teardown-all.sh
